import "./globals.css";
import {montserrat} from "./ui/fonts"


export const metadata = {
  title: "Tacticards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {//layout todo el contorno de nuestra pagina
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialised`}> 

        {children}
        <footer className="flex justify-center items-center py-10">Tacticas</footer>
      </body>
    </html>
  );
}

