import "./globals.css";
import { montserrat } from "./ui/fonts"
import Footer from "../app/components/footer/footer"

import Menu from "../app/menu"
export const metadata = {
  title: "Tacticards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {//layout todo el contorno de nuestra pagina
  return (
    <html>

      <body className={`${montserrat.className} antialised`}>

        <Menu />
        {children}
        <Footer />
      </body>


    </html>
  );
}

