import "./globals.css";
import {montserrat} from "./ui/fonts"
import Footer from "../app/components/footer/footer"
import { IoMenuOutline } from "react-icons/io5";

export const metadata = {
  title: "Tacticards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {//layout todo el contorno de nuestra pagina
  return (
    <html lang="en">
       
       

      <body className={`${montserrat.className} antialised`}> 
        <header className="HeaderBox">
        <IoMenuOutline />
          <img src="../images/Logo.png" className="TacticardsLogoHeader"></img>
        </header>
        {children}
        
      </body>
      <Footer></Footer>
    </html>
  );
}

